//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.algonquincollege.com/onlinestore")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.algonquincollege.com/onlinestore", IsNullable=false)]
public partial class BookOrders {
    
    private string channelField;
    
    private Order[] orderField;
    
    public BookOrders() {
        this.channelField = "Online";
    }
    
    /// <remarks/>
    public string Channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Order")]
    public Order[] Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.algonquincollege.com/onlinestore")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.algonquincollege.com/onlinestore", IsNullable=false)]
public partial class Order {
    
    private Customer customerField;
    
    private Item[] itemsField;
    
    /// <remarks/>
    public Customer Customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
    public Item[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.algonquincollege.com/onlinestore")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.algonquincollege.com/onlinestore", IsNullable=false)]
public partial class Customer {
    
    private ContactType customerContactField;
    
    private ShippingAddress shippingAddressField;
    
    private BillingInfo billingInfoField;
    
    /// <remarks/>
    public ContactType CustomerContact {
        get {
            return this.customerContactField;
        }
        set {
            this.customerContactField = value;
        }
    }
    
    /// <remarks/>
    public ShippingAddress ShippingAddress {
        get {
            return this.shippingAddressField;
        }
        set {
            this.shippingAddressField = value;
        }
    }
    
    /// <remarks/>
    public BillingInfo BillingInfo {
        get {
            return this.billingInfoField;
        }
        set {
            this.billingInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.algonquincollege.com/onlinestore")]
public partial class ContactType {
    
    private NameType nameField;
    
    private string emailField;
    
    private Phone[] phoneField;
    
    private string streetField;
    
    private string cityField;
    
    private ProvinceType provinceField;
    
    private string postalCodeField;
    
    /// <remarks/>
    public NameType Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Phone")]
    public Phone[] Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public ProvinceType Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.algonquincollege.com/onlinestore")]
public partial class NameType {
    
    private string firstField;
    
    private string lastField;
    
    /// <remarks/>
    public string First {
        get {
            return this.firstField;
        }
        set {
            this.firstField = value;
        }
    }
    
    /// <remarks/>
    public string Last {
        get {
            return this.lastField;
        }
        set {
            this.lastField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.algonquincollege.com/onlinestore")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.algonquincollege.com/onlinestore", IsNullable=false)]
public partial class Phone {
    
    private PhoneType typeField;
    
    private string valueField;
    
    public Phone() {
        this.typeField = PhoneType.Home;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PhoneType.Home)]
    public PhoneType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.algonquincollege.com/onlinestore")]
public enum PhoneType {
    
    /// <remarks/>
    Home,
    
    /// <remarks/>
    Office,
    
    /// <remarks/>
    Mobile,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.algonquincollege.com/onlinestore")]
public enum ProvinceType {
    
    /// <remarks/>
    ON,
    
    /// <remarks/>
    QC,
    
    /// <remarks/>
    BC,
    
    /// <remarks/>
    ALBT,
    
    /// <remarks/>
    SK,
    
    /// <remarks/>
    MB,
    
    /// <remarks/>
    NL,
    
    /// <remarks/>
    PEI,
    
    /// <remarks/>
    NB,
    
    /// <remarks/>
    NS,
    
    /// <remarks/>
    NT,
    
    /// <remarks/>
    NV,
    
    /// <remarks/>
    YK,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.algonquincollege.com/onlinestore")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.algonquincollege.com/onlinestore", IsNullable=false)]
public partial class ShippingAddress {
    
    private NameType nameField;
    
    private string streetField;
    
    private string cityField;
    
    private ProvinceType provinceField;
    
    private string postalCodeField;
    
    /// <remarks/>
    public NameType Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public ProvinceType Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.algonquincollege.com/onlinestore")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.algonquincollege.com/onlinestore", IsNullable=false)]
public partial class BillingInfo {
    
    private string creditCardNumberField;
    
    private string creditCardExpiryMonthField;
    
    private string creditCardExpiryYearField;
    
    private NameType nameField;
    
    private string streetField;
    
    private string cityField;
    
    private ProvinceType provinceField;
    
    private string postalCodeField;
    
    /// <remarks/>
    public string CreditCardNumber {
        get {
            return this.creditCardNumberField;
        }
        set {
            this.creditCardNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gMonth")]
    public string CreditCardExpiryMonth {
        get {
            return this.creditCardExpiryMonthField;
        }
        set {
            this.creditCardExpiryMonthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string CreditCardExpiryYear {
        get {
            return this.creditCardExpiryYearField;
        }
        set {
            this.creditCardExpiryYearField = value;
        }
    }
    
    /// <remarks/>
    public NameType Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public ProvinceType Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.algonquincollege.com/onlinestore")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.algonquincollege.com/onlinestore", IsNullable=false)]
public partial class Item {
    
    private string titleField;
    
    private string isbnField;
    
    private NameType firstAuthorField;
    
    private string quantityField;
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Isbn {
        get {
            return this.isbnField;
        }
        set {
            this.isbnField = value;
        }
    }
    
    /// <remarks/>
    public NameType FirstAuthor {
        get {
            return this.firstAuthorField;
        }
        set {
            this.firstAuthorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.algonquincollege.com/onlinestore")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.algonquincollege.com/onlinestore", IsNullable=false)]
public partial class Items {
    
    private Item[] itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public Item[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}
